version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "30 6 * * *"
      timezone: "Europe/Paris"

    open-pull-requests-limit: 10
    rebase-strategy: "auto"

    labels:
      - "dependencies"
      - "github-actions"

    commit-message:
      prefix: "deps(actions)"
      include: "scope"
