name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - v2

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0

      - name: Build Retype
        uses: retypeapp/action-build@latest
        env:
          RETYPE_KEY: ${{ secrets.RETYPE_KEY }}

      - name: Deploy to GitHub Pages
        uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
