name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
    - v2

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7.0.0
      with:
        fetch-depth: 0

    - name: Build Retype
      uses: retypeapp/action-build@next
      with:
        key: ${{ secrets.RETYPE_KEY }}

    - name: Deploy to GitHub Pages
      uses: retypeapp/action-github-pages@next
      with:
        update-branch: true
